name: ServerCore
version: '${project.version}'
api-version: 1.21
main: mc.xingyan.servercore.ServerCore
commands:
  test:
    usage: /test
  setrank:
    usage: /setrank <player> <rank>
  opme:
    usage: /opme
  kick:
    usage: /kick <player> [reason]
  ban:
    usage: /ban <player> [reason]
  unban:
    usage: /unban <player>
  item:
    usage: /item <item> [amount]
  skin:
    usage: /skin <player_name>|remove
  nick:
    usage: /nick <nickname>
  unnick:
    usage: /unnick
  vanish:
    usage: /vanish
  fly:
    usage: /fly
  lightning_stick:
    usage: /lightning_stick
